version: "3.9"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --blobHost 0.0.0.0 --loose
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

  mq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  azurite_data: {}
  rabbitmq_data: {}
